background #282828
foreground #D4BE98
selection_background #D4BE98
selection_foreground #282828
url_color             #d65c0d

cursor #D4BE98
cursor_text_color background
cursor_trail 1
background_opacity 0.8

# Black
color0 #3C3836
color8 #3C3836

# Red
color1 #EA6962
color9 #EA6962

# Green
color2  #A9B665
color10 #A9B665

# Yellow
color3  #D8A657
color11 #D8A657

# Blue
color4  #7DAEA3
color12 #7DAEA3

# Magenta
color5  #D3869B
color13 #D3869B

# Cyan
color6  #89B482
color14 #89B482

# White
color7  #D4BE98
color15 #D4BE98

window_padding_width 10

font_family      family='Iosevka Term' style=Extended
bold_font        family='Iosevka Term' style='Semibold Extended'
italic_font      family='Iosevka Term' style='Extended Italic'
bold_italic_font family='Iosevka Term' style='Semibold Extended Italic'
