#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#

# Default 1 monitor with 6 workspaces
bspc monitor eDP1 -d 1 2 3 4 5 6

# ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
# ║  ║ ║║║║╠╣ ║║ ╦
# ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config top_padding 40
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2
bspc config normal_border_color "#414868"
bspc config active_border_color "#c0caf5"
bspc config focused_border_color "#bb9af7"
bspc config presel_feedback_color "#7aa2f7"
bspc config window_gap 6
bspc config border_width 2
bspc config split_ratio 0.52
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# ╦ ╔╗╦ ╔═╗ ╦ ╦ ╔╦╗
# ║ ║║║ ╠═╝ ║ ║  ║
# ╩ ╩╚╝ ╩   ╚═╝  ╩

xinput set-prop "ELAN1200:00 04F3:3087 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN1200:00 04F3:3087 Touchpad" "libinput Natural Scrolling Enabled" 1

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

pgrep -x sxhkd >/dev/null || sxhkd &
feh --bg-fill $(cat ~/.cache/wallpaper) &
killall -q polybar
polybar -conf=~/.config/polybar/bspwm.ini main &
killall -q dunst
dunst &
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }
picom -b &

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D
