foreground #eceff4
background #242933

# Black
color0 #3B4252
color8 #3B4252

# Red
color1 #BF616A
color9 #BF616A

# Green
color2  #A3BE8C
color10 #A3BE8C

# Yellow
color3  #EBCB8B
color11 #EBCB8B

# Blue
color4  #81A1C1
color12 #81A1C1

# Magenta
color5  #B48EAD
color13 #b48ead

# Cyan
color6  #8FBCBB
color14 #8FBCBB

# White
color7  #D8DEE9
color15 #D8DEE9

# Cursor
cursor #D8DEE9
cursor_text_color #1a1b26

# Selection highlight
selection_foreground none
selection_background #28344a

# The color for highlighting URLs on mouse-over
url_color #9ece6a

# Window borders
active_border_color #3d59a1
inactive_border_color #101014
bell_border_color #e0af68

# Tab bar
tab_bar_style fade
tab_fade 1
active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold
inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold
tab_bar_background #101014

# Title bar
macos_titlebar_color #16161e
wayland_titlebar_color #16161e

window_padding_width 10
background_opacity 0.9
font_family      family='Iosevka Term' style=Extended
bold_font        family='Iosevka Term' style='Bold Extended'
italic_font      family='Iosevka Term' style='Extended Italic'
bold_italic_font family='Iosevka Term' style='Bold Extended Italic'
